services:
  - type: web
    name: solvenger-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOLANA_RPC_URL
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: PORT
        value: 10000 